apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: shopping-cart
  namespaceSelector:
    matchNames:
    - test
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    interval: 15s
