apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: dev
  labels:
    app: petclinic-cart
spec:
  type: ClusterIP
  selector:
    app: petclinic-cart
  ports:
  - name : metrics
    port: 80
    targetPort: 8070
